CREATE DATABASE SISTEMA;
USE SISTEMA;

CREATE TABLE GARCOM(
	IDGARCOM INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(300),
	CPF VARCHAR(11),
	DATA_NASCIMENTO VARCHAR(10),
	EMAIL VARCHAR(500),
	TELEFONE VARCHAR(11),
	SEXO CHAR(1),
	SALARIO_FIXO DOUBLE
);

CREATE TABLE MESA(
	IDMESA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NUMERO_MESA INT,
	SITUACAO VARCHAR(10),
	CAPACIDADE_MAXIMA INT,
	IDGARCOM INT,
	FOREIGN KEY (IDGARCOM) REFERENCES GARCOM (IDGARCOM)
);


